### ISSUE TITLE
Copy relative blocks, how?

### ISSUE THREAD

**Issue by JoepDiskTuna** [dmahurin/jpegrepair#3]
Not an issue really, but I can not seem to figure out what it does and what command line should look like (Windows). Is it possible to give the syntax or an example?

Thank you very much in advance.

**Comment by dmahurin** [comment]
Documentation is now added  to hopefully explain 'copy' a little.

Example given:

Copy to position 9:35 2x2 blocks from relative block 1:-20 (1 row forward, 20 columns back).

jpegprepair before.jpg after.jpg  dest 9 35 2 2 copy 1 -20
