### ISSUE TITLE
Does anyone know how jpegrepair copy command works?

### ISSUE THREAD

**Issue by JoepDiskTuna** [dmahurin/jpegrepair#4]
Does anyone know how jpegrepair copy command works? Can I have an example pls?

**Comment by zvezdochiot** [comment]
https://github.com/dmahurin/jpegrepair/blob/b52cb077cf9c7384fd2f37da4e19b838d3812b31/jpegrepair.c#L67-L68

**Comment by JoepDiskTuna** [comment]
Thanks, but I meant when using command line.

**Comment by cuuhodrc** [comment]
Is similar to delete command

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zvezdochiot** [comment]
```sh
jpegrepair lena.jpg lena.jr.jpg dest 128 128 copy 64 64
```

**Comment by JoepDiskTuna** [comment]
Brilliant, thank you! But I could also copy MCUs from one place to another in same file?

**Comment by cuuhodrc** [comment]
> Brilliant, thank you! But I could also copy MCUs from one place to another in same file?

No, because the output file is input file only

**Comment by JoepDiskTuna** [comment]
I see. Thank you!

**Comment by zvezdochiot** [comment]
Hi all!

Fixed!

---

https://github.com/dmahurin/jpegrepair/blob/b52cb077cf9c7384fd2f37da4e19b838d3812b31/jpegrepair.c#L41
to
```c
      for (block_x=0; block_x<width_in_blocks; block_x++) {
```

---

https://github.com/dmahurin/jpegrepair/blob/b52cb077cf9c7384fd2f37da4e19b838d3812b31/jpegrepair.c#L67-L69
to
```c
                    else if(op == OP_COPY)
                    {
                        ny = by + v_samp_factor * dv;
                        nx = bx + h_samp_factor * dh;
                        ny = ny % height_in_blocks;
                        nx = nx % width_in_blocks;
                        coef_buffer[by][bx][i] = coef_buffer[ny][nx][i];
                    }
```

**Comment by JoepDiskTuna** [comment]
Awesome!!! Is it possible to provide compiled win32 exe? Or am I asking too much now?

**Comment by zvezdochiot** [comment]
@JoepDiskTuna say:
>Is it possible to provide compiled win32 exe?

A little later it will be in https://github.com/ImageProcessing-ElectronicPublications/jpegrepair. Now there is no time.

**Comment by JoepDiskTuna** [comment]
Thank you very much!

**Comment by cuuhodrc** [comment]
> Thank you very much!

Could you check my email:
giaimaransomware@gmail.com

**Comment by dmahurin** [comment]
I added copy documentation and merged the block_x-width_in_blocks fix.

Thanks all.
