### ISSUE TITLE
I need help of white balance

### ISSUE THREAD

**Issue by HanalogInstruments** [dmahurin/jpegrepair#5]
Hi,

I have some photo fragmented without header and i repaired but the color look wrong like this:

**https://we.tl/t-Svv0MfqDoN**

How can i use jpegrepair to auto white balance

**Comment by zvezdochiot** [comment]
Hi @HanalogInstruments .

Use "Attach files by dragging & dropping, selecting or pasting them".

Not use https://we.tl.

**Comment by HanalogInstruments** [comment]
Here you are:
[Sample.zip](https://github.com/dmahurin/jpegrepair/files/8827700/Sample.zip)

**Comment by dmahurin** [comment]
This tool can not exactly adjust white balance or contrast.

You can adjust luminance for the whole image:

jpegrepair  /tmp/DSCN7626.jpg /tmp/DSCN7626-fixed.jpg cdelta 0 -50

If that is what you are looking for.

**Comment by HanalogInstruments** [comment]
> This tool can not exactly adjust white balance or contrast.
> 
> 
> 
> You can adjust luminance for the whole image:
> 
> 
> 
> jpegrepair  /tmp/DSCN7626.jpg /tmp/DSCN7626-fixed.jpg cdelta 0 -50
> 
> 
> 
> If that is what you are looking for.
> 
> 
> 
> 
> 
> 

Could you check the lastest issue i have open?
