### ISSUE TITLE
How i can read width and height from raw data by mcu of jpeg without header?

### ISSUE THREAD

**Issue by HanalogInstruments** [dmahurin/jpegrepair#6]
Hi,

How i can read width and height from raw data by mcu of jpeg without header?

Also i have some jpeg have wrong alginment like this and how we automate fix it by remove the mcu or pixel from jpeg

![image](https://user-images.githubusercontent.com/100456607/173756131-1631900b-dbb8-40f0-a8cd-1f801d8d0040.jpeg)

![image](https://user-images.githubusercontent.com/100456607/173756189-7a05d3ed-286b-42b0-bd5e-d8a9905451bf.jpeg)

**Comment by zvezdochiot** [comment]
Hi @HanalogInstruments

The blocks in your image are all wrong:
```sh
jpegrepair 173756131-1631900b-dbb8-40f0-a8cd-1f801d8d0040.jpeg 173756131-1631900b-dbb8-40f0-a8cd-1f801d8d0040-fix.jpeg dest 0 0 delete 48
```
![173756131-1631900b-dbb8-40f0-a8cd-1f801d8d0040-fix](https://user-images.githubusercontent.com/12370082/173831663-cf19614f-65fa-4dfb-aca6-da0c44ffe0e7.jpeg)

**Comment by dmahurin** [comment]
jpegrepair cannot determine width and height from raw data. 

Usually the image size is known by using other images from the same camera.

Once the image has a proper header
if you need to insert or delete blocks, you could do something like this:

jpegrepair  173756131-1631900b-dbb8-40f0-a8cd-1f801d8d0040.jpeg  test.jpg dest 0 0 insert 23

But as @zvezdochiot  mentioned that is not all correct. The image size is not correct in the header or blocks need to be moved with 'copy'.

**Comment by zvezdochiot** [comment]
Hi @dmahurin .

This would require a new function: `exchange`.

**Comment by HanalogInstruments** [comment]
> jpegrepair cannot determine width and height from raw data. 
> 
> 
> 
> Usually the image size is known by using other images from the same camera.
> 
> 
> 
> Once the image has a proper header
> 
> if you need to insert or delete blocks, you could do something like this:
> 
> 
> 
> jpegrepair  173756131-1631900b-dbb8-40f0-a8cd-1f801d8d0040.jpeg  test.jpg dest 0 0 insert 23
> 
> 
> 
> But as @zvezdochiot  mentioned that is not all correct. The image size is not correct in the header or blocks need to be moved with 'copy'.

Could you suggest how we use this for batch jpeg because some jpeg have difference align error like this? Also jpeg have the gray truncate from bottom of image

**Comment by dmahurin** [comment]
Hi @HanalogInstruments,  unfortunately, every image is likely different. It will be a manual process.

Your image seems to have misplaced blocks.  But even moving them does not quite align.
More investigation is needed to see if jpegrepair can be adjusted to fix this type of corruption.  It will still be manual, though.
jpegrepair  173756131-1631900b-dbb8-40f0-a8cd-1f801d8d0040.jpeg  test.jpg dest 0 0 insert 23 dest 0 0 42 23 copy 1 0

**Comment by zvezdochiot** [comment]
Apply https://github.com/dmahurin/jpegrepair/issues/6#issuecomment-1156458224:
```sh
jpegrepair 173756131-1631900b-dbb8-40f0-a8cd-1f801d8d0040.jpeg test.jpg dest 0 0 insert 23 dest 0 0 42 23 copy 1 0
```
![173756131-1631900b-dbb8-40f0-a8cd-1f801d8d0040-fix](https://user-images.githubusercontent.com/12370082/173836330-0fd43571-23f1-4a25-a98f-ca0a2412dd4d.jpeg)

**Comment by dmahurin** [comment]
@HanalogInstruments do you have the original corrupted files for these (with corrupted headers)? so we can have a better understanding of the specific corruption.

**Comment by HanalogInstruments** [comment]
> @HanalogInstruments do you have the original corrupted files for these (with corrupted headers)? so we can have a better understanding of the specific corruption.

I have some jpeg encrypted 153605 bytes from the header so only raw data without SOI-SOS

Sample:

https://drive.google.com/file/d/1emXcVGL3dWm7-ctVQT9by4_6Uie0MkzX/view?usp=drivesdk

Files I use (IMG_1333*) have standard tables - Huffman tables from JPEG standard and quantization tables for max quality (all "1").
But i need to fix information in SOF:

MCU layout (DataUnit per MCU) -> done ( s2x1.jpg ) ( same chroma sampling 4:2:2 )
Image dimensions -> i need you help to decode raw data to get width and height
https://drive.google.com/drive/folders/1Ylc61SRLVCjZ2nSla7e-8xmfg95EyMuu

Note:

use S2x1.jpg file as good header cut from SOI -> FFDA + 12 bytes
cut 0-153605 bytes ( dec ) of .jpg.nppp or jpg.wiot and merger it to the good header s2x1
because width and height from good header diffrence than the raw data from corrupted .jpg.* so we need to decode raw data and get width and height

**Comment by dmahurin** [comment]
173756189-7a05d3ed-286b-42b0-bd5e-d8a9905451bf.jpeg fixed.jpg seems to be fixed with:

jpegrepair  173756189-7a05d3ed-286b-42b0-bd5e-d8a9905451bf.jpeg fixed.jpg dest 0 0 delete 307

I was curious about 173756131-1631900b-dbb8-40f0-a8cd-1f801d8d0040.jpeg, as blocks/subblocks were in the wrong place.  Do you have the original corrupted file for this?

**Comment by HanalogInstruments** [comment]
> 173756189-7a05d3ed-286b-42b0-bd5e-d8a9905451bf.jpeg fixed.jpg seems to be fixed with:
> 
> 
> 
> jpegrepair  173756189-7a05d3ed-286b-42b0-bd5e-d8a9905451bf.jpeg fixed.jpg dest 0 0 delete 307
> 
> 
> 
> I was curious about 173756131-1631900b-dbb8-40f0-a8cd-1f801d8d0040.jpeg, as blocks/subblocks were in the wrong place.  Do you have the original corrupted file for this?

This jpeg i save on mobile maybe not here, could you check the folder wiot?

**Comment by aucuparia** [comment]
This could be of help: https://quippe.eu/blog/2016/11/17/determining-minimum-coded-unit-dimensions.html

**Comment by HanalogInstruments** [comment]
@dmahurin 
Could you read the MCU look like this via code?
I think we found how to auto algin when we read the bottom MCU lenght from the step block: and insert byte follow this blank MCU lenght to dest 0 0

[Pictures.zip](https://github.com/dmahurin/jpegrepair/files/8929241/Pictures.zip)

Example **jpegrepair input.jpg output.jpg insert 24** mcu when read from mcu have bank:

Hope you can create a special argument code to fix special error algin like this

![image_2022-06-17_233826871](https://user-images.githubusercontent.com/100456607/174340474-b4c74d18-09d7-4019-9af5-a858ca4dae02.png)

Also the non pixel border maybe difference in some files, we need to autocrop it

**Comment by dmahurin** [comment]
@HanalogInstruments 

> This could be of help: https://quippe.eu/blog/2016/11/17/determining-minimum-coded-unit-dimensions.html

This script gets the dimensions from the SOF, not from MCU.  Perhaps I misunderstand what you are suggesting.

**Comment by HanalogInstruments** [comment]
> @HanalogInstruments 
> 
> 
> 
> > This could be of help: https://quippe.eu/blog/2016/11/17/determining-minimum-coded-unit-dimensions.html
> 
> 
> 
> This script gets the dimensions from the SOF, not from MCU.  Perhaps I misunderstand what you are suggesting.

This is from SOF, i'm try suggest you this:
![image](https://user-images.githubusercontent.com/100456607/174413835-c0e3b56b-f840-4c8d-8da4-f2cf8c564276.jpeg)

**Comment by HanalogInstruments** [comment]
> @HanalogInstruments
> 
> > This could be of help: https://quippe.eu/blog/2016/11/17/determining-minimum-coded-unit-dimensions.html
> 
> This script gets the dimensions from the SOF, not from MCU. Perhaps I misunderstand what you are suggesting.

Can you try to update the width estimating & algin method from this to jpegrepair?: 
https://arxiv.org/pdf/1410.2100.pdf
https://www.sciencedirect.com/science/article/pii/S1877050916317082

**Comment by zvezdochiot** [comment]
Hi @HanalogInstruments .

Your requests far exceed both the capabilities and the actions of `jpegrepair`. Look for answers to your problems in the [IPOL Journal](https://www.ipol.im/).

**Comment by HanalogInstruments** [comment]
@dmahurin could you made a python script to insert or delete loop mcu from range like this and files save?
![image](https://user-images.githubusercontent.com/100456607/178110752-3546ede2-4e38-4d5a-a740-37ecfd61e04d.jpeg)

**Comment by zvezdochiot** [comment]
Hi @HanalogInstruments 

See https://github.com/ImageProcessing-ElectronicPublications/jpeg-decomp ,

**Comment by HanalogInstruments** [comment]
> Hi @HanalogInstruments 
> 
> 
> 
> See https://github.com/ImageProcessing-ElectronicPublications/jpeg-decomp ,
> 
> 

I have made it automate done:

https://github.com/dmahurin/jpegrepair/assets/100456607/cde45f22-1e3f-407f-a280-2e6515e47354
